include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    one_member_abstracts: false
    use_setters_to_change_properties: false
    use_key_in_widget_constructors: false
enable-experiment:
  - extension-methods
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
